-- Segurança do site GIFT Excellence — 2026
create schema if not exists gift_private;
revoke all on schema gift_private from public;

create table if not exists public.gift_site_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.gift_site_admins enable row level security;

drop policy if exists "gift_site_admins_select_self" on public.gift_site_admins;
create policy "gift_site_admins_select_self" on public.gift_site_admins
for select to authenticated using (user_id = (select auth.uid()));

revoke all on table public.gift_site_admins from anon;
grant select on table public.gift_site_admins to authenticated;

insert into public.gift_site_admins(user_id)
select id from auth.users
where email in ('giftexcellence.03@gmail.com','gabrielaegabriel1999@gmail.com')
on conflict (user_id) do nothing;

create table if not exists gift_private.gift_submission_rate_limits (
  id bigint generated by default as identity primary key,
  kind text not null,
  ip text not null,
  created_at timestamptz not null default now()
);
create index if not exists gift_submission_rate_limits_lookup
  on gift_private.gift_submission_rate_limits(kind, ip, created_at desc);

create or replace function gift_private.gift_submission_allowed(
  p_kind text, p_max_attempts integer default 8, p_window_seconds integer default 600
)
returns boolean language plpgsql volatile security definer
set search_path = gift_private, pg_temp
as $$
declare
  v_headers jsonb := coalesce(current_setting('request.headers', true), '{}')::jsonb;
  v_ip text := split_part(coalesce(v_headers->>'x-forwarded-for','unknown'), ',', 1);
  v_count integer;
begin
  delete from gift_private.gift_submission_rate_limits where created_at < now() - interval '1 day';
  select count(*) into v_count from gift_private.gift_submission_rate_limits
  where kind=p_kind and ip=v_ip and created_at >= now()-make_interval(secs=>p_window_seconds);
  if v_count >= p_max_attempts then return false; end if;
  insert into gift_private.gift_submission_rate_limits(kind,ip) values(p_kind,v_ip);
  return true;
end;
$$;
grant usage on schema gift_private to anon, authenticated;
revoke all on function gift_private.gift_submission_allowed(text,integer,integer) from public;
grant execute on function gift_private.gift_submission_allowed(text,integer,integer) to anon, authenticated;

do $$
declare t text;
begin
  foreach t in array array['gift_machines','gift_hero_slides','gift_gallery_images','gift_services','gift_site_settings','gift_quote_requests','gift_tech_support_requests','gift_contact_messages']
  loop
    execute format('drop policy if exists "%1$s public read" on public.%1$s',t);
    execute format('drop policy if exists "%1$s anon insert" on public.%1$s',t);
    execute format('drop policy if exists "%1$s auth manage" on public.%1$s',t);
    execute format('drop policy if exists "%1$s_admin_manage" on public.%1$s',t);
  end loop;
end $$;

create policy "gift_machines_public_read" on public.gift_machines for select to anon,authenticated
using(active=true);
create policy "gift_hero_slides_public_read" on public.gift_hero_slides for select to anon,authenticated
using(active=true);
create policy "gift_gallery_images_public_read" on public.gift_gallery_images for select to anon,authenticated
using(active=true);
create policy "gift_services_public_read" on public.gift_services for select to anon,authenticated
using(active=true);
create policy "gift_site_settings_public_read" on public.gift_site_settings for select to anon,authenticated using(true);

create policy "gift_quote_requests_public_insert" on public.gift_quote_requests for insert to anon,authenticated
with check(gift_private.gift_submission_allowed('quote',8,600) and length(trim(name)) between 1 and 150 and length(phone) between 5 and 60 and length(email) between 3 and 320 and length(coalesce(company,''))<=180 and length(coalesce(city_state,''))<=180 and length(coalesce(machine_interest,''))<=220 and length(coalesce(message,''))<=5000 and status='novo');
create policy "gift_tech_support_requests_public_insert" on public.gift_tech_support_requests for insert to anon,authenticated
with check(gift_private.gift_submission_allowed('tech_support',8,600) and length(trim(name)) between 1 and 150 and length(phone) between 5 and 60 and length(email) between 3 and 320 and length(equipment) between 1 and 220 and length(problem_description) between 1 and 5000 and length(coalesce(company,''))<=180 and length(coalesce(city_state,''))<=180 and status='novo');
create policy "gift_contact_messages_public_insert" on public.gift_contact_messages for insert to anon,authenticated
with check(gift_private.gift_submission_allowed('contact',8,600) and length(trim(name)) between 1 and 150 and length(email) between 3 and 320 and length(coalesce(phone,''))<=60 and length(coalesce(subject,''))<=220 and length(message) between 1 and 5000);

create policy "gift_quote_requests_admin_read" on public.gift_quote_requests for select to authenticated
using(exists(select 1 from public.gift_site_admins a where a.user_id=(select auth.uid())));
create policy "gift_tech_support_requests_admin_read" on public.gift_tech_support_requests for select to authenticated
using(exists(select 1 from public.gift_site_admins a where a.user_id=(select auth.uid())));
create policy "gift_contact_messages_admin_read" on public.gift_contact_messages for select to authenticated
using(exists(select 1 from public.gift_site_admins a where a.user_id=(select auth.uid())));

do $$
declare t text;
begin
  foreach t in array array['gift_machines','gift_hero_slides','gift_gallery_images','gift_services','gift_site_settings','gift_quote_requests','gift_tech_support_requests','gift_contact_messages']
  loop
    execute format('create policy "%1$s_admin_manage" on public.%1$s for all to authenticated using (exists(select 1 from public.gift_site_admins a where a.user_id=(select auth.uid()))) with check (exists(select 1 from public.gift_site_admins a where a.user_id=(select auth.uid())))',t);
  end loop;
end $$;

revoke all on table public.gift_machines,public.gift_hero_slides,public.gift_gallery_images,public.gift_services,public.gift_site_settings,public.gift_quote_requests,public.gift_tech_support_requests,public.gift_contact_messages from anon,authenticated;
grant select on table public.gift_machines,public.gift_hero_slides,public.gift_gallery_images,public.gift_services,public.gift_site_settings to anon;
grant select,insert,update,delete on table public.gift_machines,public.gift_hero_slides,public.gift_gallery_images,public.gift_services,public.gift_site_settings to authenticated;
grant insert on table public.gift_quote_requests,public.gift_tech_support_requests,public.gift_contact_messages to anon;
grant select,insert,update,delete on table public.gift_quote_requests,public.gift_tech_support_requests,public.gift_contact_messages to authenticated;

drop policy if exists "gift media auth upload" on storage.objects;
drop policy if exists "gift media auth update" on storage.objects;
drop policy if exists "gift media auth delete" on storage.objects;
drop policy if exists "gift_media_admin_upload" on storage.objects;
drop policy if exists "gift_media_admin_update" on storage.objects;
drop policy if exists "gift_media_admin_delete" on storage.objects;
create policy "gift_media_admin_upload" on storage.objects for insert to authenticated
with check(bucket_id='gift-excellence-media' and exists(select 1 from public.gift_site_admins a where a.user_id=(select auth.uid())));
create policy "gift_media_admin_update" on storage.objects for update to authenticated
using(bucket_id='gift-excellence-media' and exists(select 1 from public.gift_site_admins a where a.user_id=(select auth.uid())))
with check(bucket_id='gift-excellence-media' and exists(select 1 from public.gift_site_admins a where a.user_id=(select auth.uid())));
create policy "gift_media_admin_delete" on storage.objects for delete to authenticated
using(bucket_id='gift-excellence-media' and exists(select 1 from public.gift_site_admins a where a.user_id=(select auth.uid())));


-- Menor privilégio para a lista de admins
revoke all on table public.gift_site_admins from authenticated;
grant select on table public.gift_site_admins to authenticated;
